# Generated by Django 4.2.5 on 2023-09-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='image_encodings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
